"""Local analysis: V2-T5 trained per-bond gate vs bond chemistry.

Input: one or more .npz files produced by
`dump_v2_checkpoint_stats.py --per-edge-out ...`. Each npz contains:
    gate       [E]        post-sigmoid edge weight per chemical bond
    edge_attr  [E, 11]    bond-feature vector from create_data_DC.py
                          (after normalization by sum)

edge_attr columns (per create_data_DC.py:49-63):
    0: SINGLE
    1: DOUBLE
    2: TRIPLE
    3: AROMATIC
    4,5: dead (BondDir ENUM typo, always 0; see MEMORY known bugs)
    6-10: bond stereo one-hot (5 values)

For each input we compute:
    - per-bond-type mean gate (Single / Double / Triple / Aromatic)
    - Pearson correlation gate vs each edge_attr column
    - mean gate for aromatic vs non-aromatic bonds and the delta

Outputs a Markdown summary table to stdout AND writes a per-checkpoint
breakdown to paper/gate_attribution_summary.md so the result can be
quoted in the manuscript Discussion.

Usage:
    python paper/analyze_gate_per_edge.py mlp_phi_stats/*per_edge.npz
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
BOND_TYPE_COLS = [
    (0, "Single"),
    (1, "Double"),
    (2, "Triple"),
    (3, "Aromatic"),
]
STEREO_COLS = [(6 + i, f"Stereo{i}") for i in range(5)]


def _pick_bond_type(attr_row):
    """Return the name of the dominant bond type column, or '?' if unclear.

    edge_attr is row-normalized to sum to 1, so the dominant type column has
    value ~0.5 for typical bonds (one type + one stereo). Argmax over the
    type columns 0..3.
    """
    type_slice = attr_row[:4]
    if type_slice.max() <= 0:
        return "?"
    return BOND_TYPE_COLS[int(type_slice.argmax())][1]


def analyze(path):
    data = np.load(path)
    gate = data["gate"]
    attr = data["edge_attr"]
    if gate.size == 0:
        return {"path": str(path), "n_edges": 0}
    out = {
        "path": str(path),
        "n_edges": int(gate.size),
        "gate_mean": float(gate.mean()),
        "gate_std": float(gate.std()),
        "gate_q05": float(np.quantile(gate, 0.05)),
        "gate_q95": float(np.quantile(gate, 0.95)),
    }
    # Per bond type
    out["per_bond_type"] = {}
    for col, name in BOND_TYPE_COLS:
        mask = attr[:, col] > attr[:, :4].max(axis=1) * 0.5  # dominant type column
        if mask.sum() > 0:
            out["per_bond_type"][name] = {
                "n": int(mask.sum()),
                "mean": float(gate[mask].mean()),
                "std": float(gate[mask].std()),
            }
    # Aromatic vs non-aromatic dominance
    aromatic_dom = attr[:, 3] > 0.4  # row sum = 1.0; aromatic row has 0.5 in col 3
    out["aromatic_vs_other"] = {
        "n_aromatic": int(aromatic_dom.sum()),
        "n_other": int((~aromatic_dom).sum()),
        "mean_aromatic": float(gate[aromatic_dom].mean()) if aromatic_dom.sum() else None,
        "mean_other": float(gate[~aromatic_dom].mean()) if (~aromatic_dom).sum() else None,
    }
    if out["aromatic_vs_other"]["mean_aromatic"] is not None and \
       out["aromatic_vs_other"]["mean_other"] is not None:
        out["aromatic_vs_other"]["delta"] = (
            out["aromatic_vs_other"]["mean_aromatic"]
            - out["aromatic_vs_other"]["mean_other"]
        )
    # Per-column Pearson correlation
    out["pearson_vs_attr_col"] = {}
    for col, name in BOND_TYPE_COLS + STEREO_COLS:
        if attr[:, col].std() == 0:
            out["pearson_vs_attr_col"][name] = None
            continue
        r = float(np.corrcoef(gate, attr[:, col])[0, 1])
        out["pearson_vs_attr_col"][name] = round(r, 4)
    return out


def render_markdown(results):
    lines = ["# Per-edge gate attribution summary", "",
             "Generated by `paper/analyze_gate_per_edge.py`. Each row is one V2-T5",
             "checkpoint passed through `dump_v2_checkpoint_stats.py --per-edge-out`.",
             ""]
    if not results:
        return "\n".join(lines + ["(no inputs)"]) + "\n"
    # Overview table
    lines += [
        "## Per-bond-type mean gate",
        "",
        "| Checkpoint | n_edges | Single | Double | Triple | Aromatic | Other-vs-Aromatic delta |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        name = Path(r["path"]).stem
        pbt = r.get("per_bond_type", {})

        def cell(k):
            d = pbt.get(k)
            return f"{d['mean']:.3f} (n={d['n']})" if d else "--"

        delta = r.get("aromatic_vs_other", {}).get("delta")
        delta_str = f"{delta:+.3f}" if delta is not None else "--"
        lines.append(f"| {name} | {r['n_edges']} | {cell('Single')} | {cell('Double')} | "
                     f"{cell('Triple')} | {cell('Aromatic')} | {delta_str} |")
    lines += ["", "## Pearson correlation gate vs edge_attr column",
              "", "| Checkpoint | Single | Double | Triple | Aromatic | Stereo0..4 |",
              "|---|---|---|---|---|---|"]
    for r in results:
        name = Path(r["path"]).stem
        pc = r.get("pearson_vs_attr_col", {})

        def pc_cell(k):
            v = pc.get(k)
            return f"{v:+.3f}" if v is not None else "--"

        stereo_str = " / ".join(pc_cell(f"Stereo{i}") for i in range(5))
        lines.append(f"| {name} | {pc_cell('Single')} | {pc_cell('Double')} | "
                     f"{pc_cell('Triple')} | {pc_cell('Aromatic')} | {stereo_str} |")
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("paths", nargs="+", help="One or more *_per_edge.npz files")
    p.add_argument("--out", default=str(REPO / "paper" / "gate_attribution_summary.md"))
    args = p.parse_args()

    results = [analyze(Path(pth)) for pth in args.paths]
    text = render_markdown(results)
    print(text)
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"\n[ok] wrote {args.out}")


if __name__ == "__main__":
    sys.exit(main())
