"""Aggregate *_results.json into LaTeX booktabs tables.

Usage:
    python paper/make_tables.py

Reads:
    bbbp_all_results.json
    baseline_unifold_results.json
    freesolv_baseline_results.json
    freesolv_v2t5_results.json
    bace_all_results.json            (optional, produced post-B4)

Writes:
    paper/tables/main_results.tex    (cls/reg combined table)
    paper/tables/classification.tex
    paper/tables/regression.tex
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path
from typing import Optional

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = Path(__file__).resolve().parent / "tables"


def load(name: str) -> Optional[dict]:
    path = REPO / name
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def fmt(mean: float, std: Optional[float]) -> str:
    if std is None:
        return f"{mean:.3f}"
    return f"{mean:.3f} $\\pm$ {std:.3f}"


def extract_grand(seed_means: list[float]) -> tuple[float, float]:
    m = statistics.mean(seed_means)
    s = statistics.stdev(seed_means) if len(seed_means) > 1 else 0.0
    return m, s


def parse_bbbp(data: dict) -> dict[str, tuple[float, float]]:
    out = {}
    for key, label in [
        ("v0_baseline", "V0"),
        ("v2_t5_static_pair", "V2-T5"),
        ("t6_dynamic_pair_node", "T6"),
    ]:
        block = data.get(key)
        if not block:
            continue
        out[label] = (block["grand_mean"], block["std"])
    return out


def parse_bace_v0_fp(data: dict) -> dict[str, tuple[float, float]]:
    out = {}
    for key, label in [("baseline", "V0"), ("fp_only", "FP-only")]:
        block = data.get(key)
        if not block:
            continue
        s = block["summary"]
        out[label] = (s["grand_mean"], s["grand_std"])
    return out


def parse_bace_full(data: dict) -> dict[str, tuple[float, float]]:
    """Parser for post-B4 bace_all_results.json (when it exists)."""
    out = {}
    for variant_key in ("v0", "v2_t5", "t6", "fp_only"):
        block = data.get(variant_key)
        if not block:
            continue
        label = {
            "v0": "V0",
            "v2_t5": "V2-T5",
            "t6": "T6",
            "fp_only": "FP-only",
        }[variant_key]
        if "grand_mean" in block:
            out[label] = (block["grand_mean"], block.get("std", block.get("grand_std", 0.0)))
        elif "summary" in block:
            s = block["summary"]
            out[label] = (s["grand_mean"], s.get("grand_std", 0.0))
    return out


def parse_freesolv(baseline: dict, v2: dict) -> dict[str, tuple[float, float]]:
    out = {}
    if baseline:
        s = baseline["summary"]
        out["V0"] = (s["mean_rmse"], s["std_rmse"])
    if v2:
        s = v2["summary"]
        out["V2-T5"] = (s["mean_rmse"], s["std_rmse"])
    return out


def render_cls_table(bbbp: dict, bace: dict) -> str:
    variants = ["V0", "FP-only", "V2-T5", "T6"]
    lines = [
        "% Auto-generated by paper/make_tables.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Classification results (test AUC, mean $\\pm$ std over seeds, Uni-Mol fold split).}",
        "\\label{tab:classification}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Variant & BBBP & BACE \\\\",
        "\\midrule",
    ]
    for v in variants:
        bbbp_cell = fmt(*bbbp[v]) if v in bbbp else "--"
        bace_cell = fmt(*bace[v]) if v in bace else "--"
        lines.append(f"{v} & {bbbp_cell} & {bace_cell} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def render_reg_table(freesolv: dict) -> str:
    variants = ["V0", "V2-T5"]
    lines = [
        "% Auto-generated by paper/make_tables.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Regression results on FreeSolv (test RMSE, lower is better).}",
        "\\label{tab:regression}",
        "\\begin{tabular}{lc}",
        "\\toprule",
        "Variant & FreeSolv (RMSE) \\\\",
        "\\midrule",
    ]
    for v in variants:
        cell = fmt(*freesolv[v]) if v in freesolv else "--"
        lines.append(f"{v} & {cell} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def render_main_table(bbbp: dict, bace: dict, freesolv: dict) -> str:
    variants = ["V0", "FP-only", "V2-T5", "T6"]
    lines = [
        "% Auto-generated by paper/make_tables.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Main results across molecular property prediction benchmarks. "
        "Classification reports test AUC (higher is better); regression reports test RMSE (lower is better). "
        "All numbers are mean $\\pm$ std across three training seeds with Uni-Mol fold splits.}",
        "\\label{tab:main}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        " & \\multicolumn{2}{c}{Classification (AUC $\\uparrow$)} & Regression (RMSE $\\downarrow$) \\\\",
        "\\cmidrule(lr){2-3} \\cmidrule(lr){4-4}",
        "Variant & BBBP & BACE & FreeSolv \\\\",
        "\\midrule",
    ]
    for v in variants:
        bbbp_cell = fmt(*bbbp[v]) if v in bbbp else "--"
        bace_cell = fmt(*bace[v]) if v in bace else "--"
        free_cell = fmt(*freesolv[v]) if v in freesolv else "--"
        lines.append(f"{v} & {bbbp_cell} & {bace_cell} & {free_cell} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    bbbp_raw = load("bbbp_all_results.json")
    bace_v0fp_raw = load("baseline_unifold_results.json")
    bace_full_raw = load("bace_all_results.json")  # post-B4
    fs_base = load("freesolv_baseline_results.json")
    fs_v2 = load("freesolv_v2t5_results.json")

    bbbp = parse_bbbp(bbbp_raw) if bbbp_raw else {}
    bace = parse_bace_v0_fp(bace_v0fp_raw) if bace_v0fp_raw else {}
    if bace_full_raw:
        # post-B4 numbers override / extend
        bace.update(parse_bace_full(bace_full_raw))
    freesolv = parse_freesolv(fs_base, fs_v2)

    (OUT_DIR / "classification.tex").write_text(render_cls_table(bbbp, bace), encoding="utf-8")
    (OUT_DIR / "regression.tex").write_text(render_reg_table(freesolv), encoding="utf-8")
    (OUT_DIR / "main_results.tex").write_text(render_main_table(bbbp, bace, freesolv), encoding="utf-8")

    print(f"[ok] wrote tables to {OUT_DIR}")
    print(f"  bbbp variants:     {list(bbbp)}")
    print(f"  bace variants:     {list(bace)}")
    print(f"  freesolv variants: {list(freesolv)}")
    if "V2-T5" not in bace or "T6" not in bace:
        print("[warn] BACE V2-T5 / T6 missing — re-run HPC pipeline to produce bace_all_results.json")


if __name__ == "__main__":
    main()
