"""Summarize the V2-T5 / T6 / T7 trained-gate distribution from the
mlp_phi_stats/*.json files produced by dump_v2_checkpoint_stats.py.

Prints a Markdown-friendly table to stdout and writes the same content
to paper/gate_audit_summary.md for paper-side reference.

Usage:
    python paper/summarize_gate_audit.py
    python paper/summarize_gate_audit.py --stats-dir mlp_phi_stats --out paper/gate_audit_summary.md

Outputs both a one-row-per-checkpoint table and an ASCII histogram for
each checkpoint, so reviewers can sanity-check the unimodal-right-skew
claim in main.tex without needing matplotlib.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def _ascii_bar(count, max_count, width=40):
    if max_count <= 0:
        return ""
    return "#" * int(round(width * count / max_count))


def _summarize_one(payload, name):
    bias = payload.get("global_bias_b", float("nan"))
    raw = payload["raw_pre_sigmoid"]
    gate = payload["edge_weight_post_sigmoid_nonloop"]
    n = gate.get("n", 0)
    sections = [
        f"### `{name}` (n_edges={n}, bias={bias:.3f})",
        "",
        "| stream | mean | std | min | 1% | 50% | 99% | max |",
        "|---|---|---|---|---|---|---|---|",
        ("| raw_pre_sigmoid (MLP output) | "
         f"{raw['mean']:.3f} | {raw['std']:.3f} | {raw['min']:.3f} | "
         f"{raw['quantiles']['1']:.3f} | {raw['quantiles']['50']:.3f} | "
         f"{raw['quantiles']['99']:.3f} | {raw['max']:.3f} |"),
        ("| gate_post_sigmoid (per-bond weight) | "
         f"{gate['mean']:.4f} | {gate['std']:.4f} | {gate['min']:.4f} | "
         f"{gate['quantiles']['1']:.4f} | {gate['quantiles']['50']:.4f} | "
         f"{gate['quantiles']['99']:.4f} | {gate['max']:.4f} |"),
        "",
        "Gate (post-sigmoid) histogram:",
        "```",
    ]
    counts = gate["histogram"]["counts"]
    edges = gate["histogram"]["edges"]
    max_count = max(counts) if counts else 1
    for c, e_lo, e_hi in zip(counts, edges, edges[1:]):
        sections.append(f"  [{e_lo:.3f}-{e_hi:.3f}]: {c:7d}  {_ascii_bar(c, max_count)}")
    sections.append("```")
    sections.append("")
    return "\n".join(sections)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--stats-dir", default=str(REPO / "mlp_phi_stats"),
                   help="Directory of JSONs from dump_v2_checkpoint_stats.py")
    p.add_argument("--out", default=str(REPO / "paper" / "gate_audit_summary.md"))
    args = p.parse_args()

    stats_dir = Path(args.stats_dir)
    paths = sorted(stats_dir.glob("*.json"))
    if not paths:
        print(f"no JSONs under {stats_dir}")
        return 1

    rows = []
    blocks = ["# Trained-Gate Audit Summary", "",
              "Generated by `paper/summarize_gate_audit.py`. Each row is one"
              " checkpoint passed through `dump_v2_checkpoint_stats.py`.",
              ""]

    rows.append("| checkpoint | bias | raw mean | gate mean | gate std | gate q99 | n_edges |")
    rows.append("|---|---|---|---|---|---|---|")
    detail_blocks = []
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        gate = payload["edge_weight_post_sigmoid_nonloop"]
        raw = payload["raw_pre_sigmoid"]
        bias = payload.get("global_bias_b", float("nan"))
        rows.append(f"| {path.stem} | {bias:.3f} | {raw['mean']:.3f} | "
                    f"{gate['mean']:.4f} | {gate['std']:.4f} | "
                    f"{gate['quantiles']['99']:.4f} | {gate['n']} |")
        detail_blocks.append(_summarize_one(payload, path.stem))

    blocks.append("## Overview")
    blocks.append("")
    blocks.extend(rows)
    blocks.append("")
    blocks.append("## Per-checkpoint detail")
    blocks.append("")
    blocks.extend(detail_blocks)

    text = "\n".join(blocks) + "\n"
    print(text)
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"[ok] wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
